name: fake_data_generator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: 2.0.2+1
  dio: 5.4.1
  go_router: 13.2.0
  json_serializable: 6.7.1
  json_annotation: 4.8.1
  hive: 2.2.3
  google_fonts: 6.1.0
  animated_text_kit: 4.2.2
  glassmorphism: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  url_launcher: ^6.2.5
  awesome_card: ^1.1.7
  image_network: ^2.5.6
  icons_plus: ^5.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/back.png
    - assets/user.png
    - assets/address.png
    - assets/bank.png
    - assets/cc.png
    - assets/appliance.png
    - assets/blood.png
